const OptionEscolar = () =>{
    return(
        <>
          <option value="">none</option>
          <option value="abrochadoras-de-mesa">Abrochadoras de Mesa</option>
          <option value="accesorios-para-dibujo-tecnico">Accesorios para Dibujo Tecnico</option>
          <option value="accesorios-para-manualidades">Accesorios para Manualidades</option>
          <option value="accesorios-de-madera">Accesorios de Madera</option>
          <option value="accesorios-para-pizarras-y-pizarrones">Accesorios para Pizarras y Pizarrones</option>
          <option value="accesorios-para-artistica">Accesorios para Artistica</option>
          <option value="acetatos">Acetatos</option>
          <option value="acuarelas">Acuarelas</option>
          <option value="adhesivos-escolares">Adhesivos Escolares</option>
          <option value="adhesivos-varios">Adhesivos Varios</option>
          <option value="alfileres-y-chinches">Alfileres y Chinches</option>
          <option value="anotadores">Anotadores</option>
          <option value="aros-para-carpetas">Aros para Carpetas</option>
          <option value="atriles">Atriles</option>
          <option value="bandas-elasticas">Bandas Elasticas</option>
          <option value="banderas-escarapelas-y-cintas">Banderas Escarapelas y Cintas</option>
          <option value="bastidores">Bastidores</option>
          <option value="biblioratos">Biblioratos</option>
          <option value="blocks">Blocks</option>
          <option value="boligrafos">Boligrafos</option>
          <option value="borratintas">Borratintas</option>
          <option value="botellas-y-termos">Botellas y Termos</option>
          <option value="brillantina/gibre/purpurina">Brillantina/Gibre/Purpurina</option>
          <option value="broches-para-abrochadoras">Broches para Abrochadoras</option>
          <option value="broches-varios">Broches Varios</option>
          <option value="cajas-con-elastico">Cajas con Elastico</option>
          <option value="calculadoras">Calculadoras</option>
          <option value="canoplas">Canoplas</option>
          <option value="carpetas">Carpetas</option>
          <option value="carpetas-escolares">Carpetas Escolares</option>
          <option value="carteleras-y-planchas-de-corchos">Carteleras y Planchas de Corchos</option>
          <option value="carton">Carton</option>
          <option value="carton-enetelado">Carton Enetelado</option>
          <option value="cartuchos-y-tanques">Cartuchos y Tanques</option>
          <option value="cartulina">Cartulina</option>
          <option value="chinches-y-alfileres">Chinches y Alfileres</option>
          <option value="cintas-adhesivas">Cintas Adhesivas</option>
          <option value="clips">Clips</option>
          <option value="compases">Compases</option>
          <option value="conjuntos-geometricos">Conjuntos Geometricos</option>
          <option value="constituciones-y-reglamentos">Constituciones y Reglamentos</option>
          <option value="correctores">Correctores</option>
          <option value="crayones-y-pasteles">Crayones y Pasteles</option>
          <option value="cuadernillos">Cuadernillos</option>
          <option value="cuadernos-16/21">Cuadernos 16/21</option>
          <option value="cuadernos-16/21-forrados">Cuadernos 16/21 Forrados</option>
          <option value="cuadernos-19/24">Cuadernos 19/24</option>
          <option value="cuadernos-21/27">Cuadernos 21/27</option>
          <option value="cuadernos-29/7">Cuadernos 29/7</option>
          <option value="cuadernos-comerciales">Cuadernos Comerciales</option>
          <option value="cuadernos-especiales">Cuadernos Especiales</option>
          <option value="diccionarios">Diccionarios</option>
          <option value="escuadras">Escuadras</option>
          <option value="espirales-para-anillados">Espirales para Anillados</option>
          <option value="etiquetas-autoadhesivas">Etiquetas Autoadhesivas</option>
          <option value="fibrofacil">Fibrofacil</option>
          <option value="fichas-y-ficheros">Fichas y Ficheros</option>
          <option value="flautas">Flautas</option>
          <option value="folios">Folios</option>
          <option value="fundas-y-laminas-para-forrar">Fundas y Laminas para Forrar</option>
          <option value="globos-terraqueos">Globos Terraqueos</option>
          <option value="goma-eva">Goma Eva</option>
          <option value="gomas-de-borrar">Gomas de Borrar</option>
          <option value="hilos">Hilos</option>
          <option value="imanes">Imanes</option>
          <option value="indices">Indices</option>
          <option value="juegos">Juegos</option>
          <option value="kits-y-set-infantiles">Kits y Set Infantiles</option>
          <option value="laminas-y-albumes-educativos">Laminas y Albumes Educativos</option>
          <option value="lapiceras-pluma">Lapiceras Pluma</option>
          <option value="lapices-de-colores">Lapices de Colores</option>
          <option value="lapices-de-grafito">Lapices de Grafito</option>
          <option value="libretas">Libretas</option>
          <option value="libros-infantiles">Libros Infantiles</option>
          <option value="luncheras-y-tuppers">Luncheras y Tuppers</option>
          <option value="lupas">Lupas</option>
          <option value="mapas">Mapas</option>
          <option value="maquinas-varias">Maquinas Varias</option>
          <option value="marcadores">Marcadores</option>
          <option value="masas-para-moldear">Masas para Moldear</option>
          <option value="mezcladores">Mezcladores</option>
          <option value="minas">Minas</option>
          <option value="mochilas">Mochilas</option>
          <option value="notas-adhesivas">Notas Adhesivas</option>
          <option value="ojalillo">Ojalillo</option>
          <option value="oleos-y-temperas-profecionales">Oleos y Temperas Profecionales</option>
          <option value="palitos-helado-y-brochetas">Palitos Helado y Brochetas</option>
          <option value="papel">Papel</option>
          <option value="perforadoras">Perforadoras</option>
          <option value="pinceles">Pinceles</option>
          <option value="pintorcitos">Pintorcitos</option>
          <option value="pinturas">Pinturas</option>
          <option value="pinza-abrochadora">Pinza Abrochadora</option>
          <option value="pistolas-encoladoras">Pistolas Encoladoras</option>
          <option value="pizarras-y-pizarrones">Pizarras y Pizarrones</option>
          <option value="placas-portapapeles">Placas Portapapeles</option>
          <option value="plastilinas">Plastilinas</option>
          <option value="plastipinturitas">Plastipinturitas</option>
          <option value="plumines-y-respuestos-de-plumas">Plumines y Respuestos de Plumas</option>
          <option value="portaminas">Portaminas</option>
          <option value="portalapices-y-portatarjetas">Portalapices y Portatarjetas</option>
          <option value="portaminas">Portaminas</option>
          <option value="portarrollos">Portarrollos</option>
          <option value="reglas">Reglas</option>
          <option value="respuestos-de-dibujos">Respuestos de Dibujos</option>
          <option value="respuestos-especiales">Respuestos Especiales</option>
          <option value="respuestos-rayados-y-cuadriculados">Respuestos Rayados y Cuadriculados</option>
          <option value="resaltadores">Resaltadores</option>
          <option value="resmas">Resmas</option>
          <option value="rollers-ball">Rollers Ball</option>
          <option value="rollos-de-pvc">Rollos de PVC</option>
          <option value="sacapuntas">Sacapuntas</option>
          <option value="separadores">Separadores</option>
          <option value="sobres-para-plastificar">Sobres para Plastificar</option>
          <option value="tablas-periodicas">Tablas Periodicas</option>
          <option value="telgopor">Telgopor</option>
          <option value="temperas-escolares">Temperas Escolares</option>
          <option value="tijeras">Tijeras</option>
          <option value="tintas-varias">Tintas Varias</option>
          <option value="tizas-para-pizarra">Tizas para Pizarra</option>
          <option value="transportadores">Transportadores</option>
          <option value="vasos-y-tazas">Vasos y Tazas</option>
        </> 
    )
}
export default OptionEscolar