const OptionComercial = () =>{
    return(
        <>
          <option value="">none</option>
          <option value="abrochadoras-de-mesa">Abrochadoras de Mesa</option>
          <option value="accesorios-para-pizarras-y-pizarrones">Accesorios para Pizarras y Pizarrones</option>
          <option value="accesorios-para-artistica">Accesorios para Artistica</option>
          <option value="adhesivos-escolares">Adhesivos Escolares</option>
          <option value="adhesivos-varios">Adhesivos Varios</option>
          <option value="alfileres-y-chinches">Alfileres y Chinches</option>
          <option value="almohadillas">Almohadillas</option>
          <option value="anotadores">Anotadores</option>
          <option value="aprietapapeles">Aprietapapeles</option>
          <option value="arandelas-y-tornillos">Arandelas y Tornillos</option>
          <option value="atriles">Atriles</option>
          <option value="bandas-elasticas">Bandas Elasticas</option>
          <option value="bandejas-para-papeles">Bandejas para Papeles</option>
          <option value="banderas-escarapelas-y-cintas">Banderas Escarapelas y Cintas</option>
          <option value="biblioratos">Biblioratos</option>
          <option value="blocks">Blocks</option>
          <option value="bobinas-de-papel-para-regalos">Bobinas de Papel para Regalos</option>
          <option value="boligrafos">Boligrafos</option>
          <option value="bolsas-para-regalos">Bolsas para Regalos</option>
          <option value="broches-para-abrochadoras">Broches para Abrochadoras</option>
          <option value="broches-varios">Broches Varios</option>
          <option value="cajas">Cajas</option>
          <option value="cajas-con-elastico">Cajas con Elastico</option>
          <option value="calculadoras">Calculadoras</option>
          <option value="calendarios">Calendarios</option>
          <option value="carbonicos">Carbonicos</option>
          <option value="carpetas">Carpetas</option>
          <option value="carteleras-y-planchas-de-corchos">Carteleras y Planchas de Corchos</option>
          <option value="cartuchos-y-tanques">Cartuchos y Tanques</option>
          <option value="cestos-papeleros">Cestos Papeleros</option>
          <option value="chinches-y-alfileres">Chinches y Alfileres</option>
          <option value="cintas-adhesivas">Cintas Adhesivas</option>
          <option value="cintas-para-maquina-e-impresoras">Cintas para Maquina e Impresoras</option>
          <option value="cintas-y-rodillos">Cintas y Rodillos</option>
          <option value="cizallas-y-guillotinas">Cizallas y Guillotinas</option>
          <option value="clasificadores">Clasificadores</option>
          <option value="clips">Clips</option>
          <option value="cofres">Cofres</option>
          <option value="correctores">Correctores</option>
          <option value="cortantes-y-cuchillas">Cortantes y Cuchillas</option>
          <option value="cuadernillos">Cuadernillos</option>
          <option value="cuadernos-16/21">Cuadernos 16/21</option>
          <option value="cuadernos-16/21-forrados">Cuadernos 16/21 Forrados</option>
          <option value="cuadernos-19/24">Cuadernos 19/24</option>
          <option value="cuadernos-21/27">Cuadernos 21/27</option>
          <option value="cuadernos-29/7">Cuadernos 29/7</option>
          <option value="cuadernos-comerciales">Cuadernos Comerciales</option>
          <option value="cuadernos-especiales">Cuadernos Especiales</option>
          <option value="detector-de-billetes">Detector de Billetes</option>
          <option value="engrampadoras">Engrampadoras</option>
          <option value="espirales-para-anillados">Espirales para Anillados</option>
          <option value="etiquetas-autoadhesivas">Etiquetas Autoadhesivas</option>
          <option value="etiquetas-manila">Etiquetas Manila</option>
          <option value="exhibidores">Exhibidores</option>
          <option value="fichas-y-ficheros">Fichas y Ficheros</option>
          <option value="folios">Folios</option>
          <option value="formularios-comerciales">Formularios Comerciales</option>
          <option value="formularios-continuos">Formularios Continuos</option>
          <option value="globos-terraqueos">Globos Terraqueos</option>
          <option value="gomas-de-borrar">Gomas de Borrar</option>
          <option value="hilos">Hilos</option>
          <option value="imanes">Imanes</option>
          <option value="indices">Indices</option>
          <option value="lapiceras-pluma">Lapiceras Pluma</option>
          <option value="lapices-de-grafito">Lapices de Grafito</option>
          <option value="libretas">Libretas</option>
          <option value="libros-comerciales">Libros Comerciales</option>
          <option value="lupas">Lupas</option>
          <option value="mapas">Mapas</option>
          <option value="maquinas-varias">Maquinas Varias</option>
          <option value="marcadores">Marcadores</option>
          <option value="minas">Minas</option>
          <option value="mojadedos">Mojadedos</option>
          <option value="notas-adhesivas">Notas Adhesivas</option>
          <option value="ojalillo">Ojalillo</option>
          <option value="organizadores-y-planificadores">Organizadores y Planificadores</option>
          <option value="papel">Papel</option>
          <option value="perforadoras">Perforadoras</option>
          <option value="pincha-papeles">Pincha Papeles</option>
          <option value="pinza-abrochadora">Pinza Abrochadora</option>
          <option value="pizarras-y-pizarrones">Pizarras y Pizarrones</option>
          <option value="placas-portapapeles">Placas Portapapeles</option>
          <option value="portaclips">Portaclips</option>
          <option value="portacredenciales-y-accesorios">Portacredenciales y Accesorios</option>
          <option value="portalaminas">Portalaminas</option>
          <option value="portalapices-y-portatarjetas">Portalapices y Portatarjetas</option>
          <option value="portaminas">Portaminas</option>
          <option value="portarrollos">Portarrollos</option>
          <option value="portatacos-para-papeles">Portatacos para Papeles</option>
          <option value="respuestos-especiales">Respuestos Especiales</option>
          <option value="respuestos-rayados-y-cuadriculados">Respuestos Rayados y Cuadriculados</option>
          <option value="resaltadores">Resaltadores</option>
          <option value="resmas">Resmas</option>
          <option value="rollers-ball">Rollers Ball</option>
          <option value="rollos-de-pvc">Rollos de PVC</option>
          <option value="rollos-para-maquina">Rollos para Maquina</option>
          <option value="rollos-varios">Rollos Varios</option>
          <option value="sacabroches">Sacabroches</option>
          <option value="sacapuntas">Sacapuntas</option>
          <option value="sellos">Sellos</option>
          <option value="separadores">Separadores</option>
          <option value="sobres">Sobres</option>
          <option value="sobres-para-plastificar">Sobres para Plastificar</option>
          <option value="talonarios-comerciales">Talonarios Comerciales</option>
          <option value="tapas-para-anillado">Tapas para Anillado</option>
          <option value="tarjetas-opalinas-y-tacos">Tarjetas Opalinas y Tacos</option>
          <option value="tijeras">Tijeras</option>
          <option value="tintas-varias">Tintas Varias</option>
          <option value="tizas-para-pizarra">Tizas para Pizarra</option>
        </> 
    )
}
export default OptionComercial